// generated by "sampctl package init"
#include <a_samp>
#include <itemtasks>

main() {}

public OnGameModeInit() {
    new ItemType:item_Marijuana = DefineItemType("Marijuana", "Marijuana", 3027, 1, 0.0);
    new ItemType:item_Toolbox = DefineItemType("Toolbox", "Toolbox", 19921, 1, 0.0);
    new ItemType:item_Tire = DefineItemType("Tire", "Tire", 1098, 1, 0.0);


    ItemTasks_DefineItemType(item_Marijuana, 20);
    ItemTasks_DefineItemType(item_Toolbox, 5);
    ItemTasks_DefineItemType(item_Tire, 2);

    Player_SetRandomTask(0);
    printf("----------------------------------------");
    Player_SetRandomTask(1);
    printf("----------------------------------------");
    Player_SetRandomTask(2);
    printf("----------------------------------------");

    new ItemType:items[3];
    items[0] = item_Marijuana;
    items[1] = item_Marijuana;
    items[2] = item_Toolbox;

    Player_SetTask(3, items);

    new ItemType:arr[ITEMTASKS_MAX_ITEMS_PER_TASK];

    Player_GetActiveTaskItemTypes(1, arr);

    for (new i = 0; i < sizeof(arr); i++) {
        printf("Item: %d", _:arr[i]);
    }

    Player_CompleteTask(1);
}